language: cpp
os: linux
compiler: g++
addons:
    apt:
        sources:
            - kalakris-cmake
            - boost-latest
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - cmake-data
            - zlib1g-dev
            - libprotobuf-dev
            - protobuf-compiler 
            - libboost1.55-all-dev
            - gcc-5
            - g++-5
            - clang
before_script:
  - cd core
  - mkdir build
  - cd build
  - cmake ..

script: make