language: cpp
compiler: gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
    apt:
        sources:
            - kalakris-cmake
            - boost-latest
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
            - ubuntu-toolchain-r-test
        packages:   
            - cmake
            - cmake-data
            - libboost1.59-all-dev
            - protobuf-compiler 
            - libprotobuf-dev
            - zlib1g-dev
            - gcc-4.8
            - g++-4.8
            - clang
before_script:
  - cd core
  - mkdir build
  - cd build
  - cmake ..

script: make