sude: false
language: cpp
os: linux
compiler: gcc
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
    apt:
        sources:
            - kalakris-cmake
            - george-edison55-precise-backports # cmake 3.x
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - cmake
            - cmake-data
            - zlib1g-dev
            - libprotobuf-dev
            - protobuf-compiler
            - libboost1.55-all-dev
            - gcc-4.9
            - g++-4.9
            - clang
before_script:
    - cd core
    - mkdir build
    - cd build
    - cmake ..
script:
    - make
    - cd test
    - ./Test #--log_level=all
    - ctest -V
